FROM node:20-alpine as base
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /app
COPY package*.json ./
EXPOSE 3000

# Phase de développement
FROM base as dev
ENV NODE_ENV=development
RUN npm install
CMD ["npm", "run", "dev"]